aspace_backup_cron:
  minute: '2'
  hour: '4'
  day: '*'
  month: '*'
  weekday: '*'
archivesspace_backup_dir: /backup
archivesspace_migrations_dir: "{{ archivesspace_backup_dir }}/migrations"
archivesspace_rotations_dir: "{{ archivesspace_backup_dir }}/rotations"
archivesspace_download_url: "https://github.com/archivesspace/archivesspace/releases/download/{{archivesspace_version}}/archivesspace-{{archivesspace_version}}.zip"
archivesspace_home: "{{ archivesspace_root}}/archivesspace"
archivesspace_jdbc_version: 5.1.39
archivesspace_rebuild_index: no
archivesspace_restore_s3_filename: restore.sql.gz
archivesspace_restore_s3_path: "path/to/restore/dir"
archivesspace_restore_type: mysqldump
archivesspace_role_mode: "not set" # should be one of [ fresh, restor, upgrade ]
archivesspace_root: /opt
archivesspace_src: "{{ archivesspace_root}}/archivesspace-{{ archivesspace_version }}/archivesspace"
archivesspace_unzip_target: "{{ archivesspace_root}}/archivesspace-{{ archivesspace_version }}"
archivesspace_version: v2.3.2
