- name: install ferm
  apt:
    name: ferm
    force: yes
    cache_valid_time: 86400

- name: Enable ferm
  lineinfile:
    regexp: 'ENABLED="no"'
    line: 'ENABLED="yes"'
    dest: /etc/default/ferm

- name: set iptables conf
  template:
    src: ferm.conf.j2
    dest: /etc/ferm/ferm.conf
    owner: root
    group: root

- name: Load iptables configuration
  command: ferm /etc/ferm/ferm.conf
