---
- name: htop
  apt: 
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: 86400
  with_items:
    - htop
    - unzip
    - emacs
    - ntp
    - tree

- name: install ferm
  apt:
    name: ferm
    force: yes
    cache_valid_time: 86400

- name: Enable ferm
  lineinfile:
    regexp: 'ENABLED="no"'
    line: 'ENABLED="yes"'
    dest: /etc/default/ferm

- name: set iptables conf
  template: 
    src: ferm.conf.j2
    dest: /etc/ferm/ferm.conf
    owner: root
    group: root

- name: Load iptables configuration
  command: ferm /etc/ferm/ferm.conf

- name: Configure ntp
  lineinfile:
    line: "server ntp1.lsu.edu"
    insertbefore: "server 0.ubuntu.pool.ntp.org"
    dest: /etc/ntp.conf

- name: Set timezone
  command: timedatectl set-timezone America/Chicago

- name: Restart ntp
  service:
    name: ntp
    state: restarted
