---
- name: htop
  apt:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: 86400
  with_items:
    - htop
    - unzip
    - emacs
    - tree

- include: ferm.yml
  when: ferm_enabled

- include: ntp.yml
