---
- name: Create backup
  command: "{{ archivesspace_home }}/scripts/backup.sh --output {{ archivesspace_backup_dir }}/before-update-to-{{ archivesspace_version }}.zip"

- name: Ensure backup is readable
  file:
    path: "{{ archivesspace_home }}/scripts/backup.sh --output {{ archivesspace_backup_dir }}/before-update-to-{{ archivesspace_version }}.zip"
    mode: "0744"
