---
- set_fact:
    fetch: "{{ fetch_data}}"

- name: get pip
  apt:
    name: python-pip
  when: fetch

- name: get mysql lib
  apt:
    name: python-mysqldb
  when: fetch

- name: get aws cli
  pip:
    name: awscli
  when: fetch

- name: make aws config dir
  file:
    path: /root/.aws
    state: directory
  when: fetch

- name: configure aws cli
  template:
    src: templates/awsconfig.j2
    dest: /root/.aws/config
  when: fetch

- name: get latest db from s3
  command: "aws s3 cp s3://{{ bucket }}/latest/daily_archivesspace.sql.gz /opt/"
  when: fetch

- name: import db
  mysql_db:
    target: /opt/daily_archivesspace.sql.gz
    db: archivesspace
    config_file: /root/.my.cnf
    state: import
  when: fetch
