---
- name: get pip
  apt:
    name: python-pip

- name: get mysql lib
  apt:
    name: python-mysqldb

- name: get aws cli
  pip:
    name: awscli

- name: make aws config dir
  file:
    path: /root/.aws
    state: directory

- name: configure aws cli
  template:
    src: templates/awsconfig.j2
    dest: /root/.aws/config

- name: get latest db from s3
  command: "aws s3 cp s3://{{ bucket }}/latest/daily_archivesspace.sql.gz /opt/"

- name: import db
  mysql_db:
    target: /opt/daily_archivesspace.sql.gz
    db: archivesspace
    config_file: /root/.my.cnf
    state: import
