---
- include: fresh_install.yml
  when: ansible_role_archivesspace_mode == 'fresh'

- include: upgrade.yml
  when: ansible_role_archivesspace_mode == 'upgrade'

- include: restore.yml
  when: ansible_role_archivesspace_mode == 'restore'
