---
- include: fresh_install.yml
  when: archivesspace_role_mode == 'fresh'

- include: upgrade.yml
  when: archivesspace_role_mode == 'upgrade'

- include: restore.yml
  when: archivesspace_role_mode == 'restore'
