---

- name: Check if we have already fetched the source for this version.
  stat:
    path: "{{ archivesspace_unzip_target }}/archivesspace"
  register: unzipped

- name: Ensure Aspace home directory exists.
  file:
    path: "{{ archivesspace_unzip_target }}"
    state: directory

- name: Unzip AS
  unarchive:
    src: "{{ archivesspace_download_url }}"
    dest: "{{ archivesspace_unzip_target }}"
    copy: no
  when: unzipped.stat.exists == false

- name: make symlink
  file:
    path: "{{ archivesspace_home }}"
    src: "{{ archivesspace_unzip_target }}/archivesspace"
    state: link
    force: yes

- name: service exists ?
  stat:
    path: /etc/init.d/archivesspace
  register: service_exists

- name: Stop archivesspace.
  service:
    name: archivesspace
    state: stopped

- name: Wait for 8080 to close
  wait_for: 
    port: 8080
    state: absent

- name: Wait for 8089 to close
  wait_for: 
    port: 8089
    state: absent

# Setup user-defined fields
- include: user-defined-fields.yml

- name: Get mysql connector
  get_url: 
    url: "http://central.maven.org/maven2/mysql/mysql-connector-java/{{ jdbc_version }}/mysql-connector-java-{{ jdbc_version }}.jar"
    dest: "{{ archivesspace_src }}/lib/"

# @TODO may need to define an archivesspace restart handler to pickup changes here
# @TODO also figure out how to prevent lineinfiles from going to EOF
- name: Set log level
  lineinfile:
    state: present
    line: 'AppConfig[:backend_log_level] = "warn"'
    insertafter: '#AppConfig[:backend_log_level] = "debug"'
    dest: "{{ archivesspace_src }}/config/config.rb"

- name: configure connector
  lineinfile:
    state: present
    line: "AppConfig[:db_url] = \"jdbc:mysql://{{ mysql_host }}:3306/archivesspace?user={{ mysql_user }}&password={{ mysql_pass }}&useUnicode=true&characterEncoding=UTF-8\""
    insertafter: EOF
    dest: "{{ archivesspace_src }}/config/config.rb"

- include: fetch_data.yml
  when: fetch_data
    
- name: run db insert script
  command: "sh {{ archivesspace_src }}/scripts/setup-database.sh"
#  when: "aspace_link.stat.islnk == false or (aspace_link.stat.islnk is defined and aspace_link.stat.lnk_source != '{{ archivesspace_src }}')"

- name: check init script exists
  stat: 
    path: /etc/init.d/archivesspace
  register: init_exists

#- name: migrate data
#  command: "cp -rL {{ archivesspace_home }}/{{ item }}/ {{ archivesspace_src }}/{{ item }}"
#  with_items:
#    - data
#  when: "aspace_link.stat.islnk is not defined or aspace_link.stat.lnk_source != {{ archivesspace_src }}"

# this can go after the upgrade to 142 on prod and staging
- name: Remove initial directory
  file:
    path: "{{ archivesspace_home }}"
    state: absent
  when: aspace_link.stat.isdir == true

- name: Ensure symlink exists
  file:
    path: "{{ archivesspace_home }}"
    src: "{{ archivesspace_src }}"
    state: link
    force: true

- name: setup init script
  file: 
    path: "/etc/init.d/archivesspace"
    src:  "{{ archivesspace_home }}/archivesspace.sh"
    state: link

- name: ensure runlevel
  command: "update-rc.d archivesspace defaults"

#- name: Ensure that archivesspace is started
#  command: /etc/init.d/archivesspace start

# setup Jasper reporting
- include: jasper.yml

- name: Start the app
  service: 
    name:    archivesspace
    state:   started
    enabled: yes
  environment: 
    JAVA_FONTS: /usr/share/fonts/truetype

- wait_for: 
    port: 8080
    delay: 30

- name: Ensure that backup dir exists
  file:
    state: directory
    path: /backup
