- name: service exists ?
  stat:
    path: /etc/init.d/archivesspace
  register: service_exists

- name: Stop archivesspace.
  service:
    name: archivesspace
    state: stopped
  when: service_exists.stat.exists

- name: Wait for 8080 to close
  wait_for: 
    port: 8080
    state: absent

- name: Wait for 8089 to close
  wait_for: 
    port: 8089
    state: absent
