---
- hosts: all
  become: yes
  tasks:
  - name: get pip
    apt:
      name: python-pip

  - name: get aws cli
    pip:
      name: awscli

  - name: make aws config dir
    file:
      path: /root/.aws
      state: directory

  - name: configure aws cli
    template:
      src: templates/awsconfig.j2
      dest: /root/.aws/config

  - name: cron sync mysql to s3 # requires that ec2 instance is configured with an appropriate IAM role.
    cron:
      name: "s3 sync"
      minute: "{{ automysqlbackup_cron.minute }}"
      hour: "{{ automysqlbackup_cron.hour }}"
      day: "{{ automysqlbackup_cron.day }}"
      month: "{{ automysqlbackup_cron.month }}"
      weekday: "{{ automysqlbackup_cron.weekday }}"
      user: root
      job: "/usr/local/bin/aws s3 sync /var/lib/automysqlbackup/ s3://{{ bucket }}/backup/{{ aws_user_name }}"
