---
- hosts: all
  become: true
  gather_facts: false
  pre_tasks:
  - name: Install python for Ansible
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    changed_when: False

  # Manually gather facts once python is installed
  - name: gather facts
    setup:
  vars:
    ansible_role_archivesspace_mode: 'fresh'
    archivesspace_enable_jasper: yes
    archivesspace_version: v1.4.2
  roles:
    - common
    - ansible-role-apache
    - ansible-role-git
    - ansible-role-mysql
    - ansible-role-java
    - archivesspace
    - ansible-role-s3-sync
    - ansible-role-rotate-backups
