  - openssl_dhparam:
      path: "{{ ansible_openssl_dhparam_path }}"
      size: 2048

  - name: Configure apache ssl params
    template:
      src: templates/ssl-params.conf.j2
      dest: /etc/apache2/conf-available/ssl-params.conf

  - name: Enable ssl-conf
    command: a2enconf ssl-params

  - name: Copy cert
    copy:
      src: "files/aspace.crt"
      dest: "{{ aspace_proxy_cert_path }}/{{ aspace_proxy_cert_filename }}"

  - name: Copy chain
    copy:
      src: "files/{{ aspace_proxy_chain_filename }}"
      dest: "{{ aspace_proxy_cert_path }}/{{ aspace_proxy_cert_filename }}"
    when: aspace_proxy_ssl_use_chain

  - name: Copy keys
    copy:
      src: "files/{{ item }}"
      dest: "{{ aspace_proxy_key_path }}/{{ item }}"
    with_items:
      - "{{ aspace_proxy_key_filename }}"

  - name: Restart apache2
    service:
      name: apache2
      state: restarted
