---
- hosts: all
  become: true
  gather_facts: false
  pre_tasks:
  - name: Install python for Ansible
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    changed_when: False

  # Manually gather facts once python is installed
  - name: gather facts
    setup:

  - name: get pip
    apt:
      name: python-pip

    # http://en.enisozgen.com/ansible-check-is-command-exist/
  - name: Check is aws installed
    shell: command -v aws >/dev/null 2>&1
    register: is_aws_exist
    ignore_errors: yes

  - name: get aws cli
    pip:
      name: awscli
    when: is_aws_exist.rc != 0

  vars:
    archivesspace_role_mode: 'fresh'
    archivesspace_version: v2.3.2

  roles:
    - common
    - ansible-timedatectl
    - ansible-role-apache
    - ansible-role-git
    - ansible-role-mysql
    - ansible-role-java
    - archivesspace
    - { role: ansible-role-s3-sync, when: archivesspace_install_s3_sync }
    - ansible-role-rotate-backups


  post_tasks:
    # this should prob be somewhere neater.
  - name: cron sync to s3
    cron:
      name: "migrations sync"
      minute: "{{ s3_sync_cron.minute }}"
      hour: "{{ s3_sync_cron.hour }}"
      day: "{{ s3_sync_cron.day }}"
      month: "{{ s3_sync_cron.month }}"
      weekday: "{{ s3_sync_cron.weekday }}"
      user: "{{ s3_sync_agent_linux_username }}"
      job: "{{ s3_sync_aws_cli_bin_location }} s3 sync {{ archivesspace_migrations_dir }}/ s3://{{ s3_sync_bucket }}/{{ archivesspace_s3_migrations_folder }}"
    when: archivesspace_install_s3_sync

  - name: cron sync (with delete) to s3 # requires that ec2 instance is configured with an appropriate IAM role.
    cron:
      name: "s3 sync"
      minute: "{{ s3_sync_cron.minute }}"
      hour: "{{ s3_sync_cron.hour }}"
      day: "{{ s3_sync_cron.day }}"
      month: "{{ s3_sync_cron.month }}"
      weekday: "{{ s3_sync_cron.weekday }}"
      user: "{{ s3_sync_agent_linux_username }}"
      job: "{{ s3_sync_aws_cli_bin_location }} s3 sync --delete {{ archivesspace_rotations_dir }}/ s3://{{ s3_sync_bucket }}/{{ archivesspace_s3_rotations_folder }}"
    when: archivesspace_install_s3_sync

    # Ensure our DR user can login
  - import_playbook: playbook-backup-admin.yml
