---
- hosts: all
  become: true
  vars_files:
    - vars
  roles:
    - common
#    - iptables
    - ansible-role-git
    - ansible-role-mysql
    - ansible-role-java
    - archivesspace
    - ansible-automysqlbackup
