---
- hosts: all
  become: true
  roles:
    - common
    - ansible-role-apache
    - ansible-role-git
    - ansible-role-mysql
    - ansible-role-java
    - archivesspace
    - ansible-automysqlbackup
