---
- hosts: all
  become: yes
  vars:
    passrandom: "{{ lookup('password', ansible_random_password_dir + '/' + 'mysql' + '.' + ansible_random_password_ext + ' chars=ascii_letters,digits,hexdigits length=45') }}"
  tasks:

  - debug:
      var: passrandom

  - debug:
      var: passrandom
