---
- hosts: all
  become: yes
  tasks:
  - name: Ensure java memory is set
    lineinfile:
      line: 'export ASPACE_JAVA_XMX="-Xmx2048m"'
      path: /etc/init.d/archivesspace
      insertafter: "### END INIT INFO"
