    apache_vhosts_ssl:
      - servername: "{{ aspace_proxy_production_hostname }}"
        serveradmin: "{{ aspace_proxy_apache_email }}"
        certificate_file: "{{ aspace_proxy_cert_path }}/{{ aspace_proxy_cert_filename }}"
        certificate_chain_file: "{{ aspace_proxy_cert_path }}/{{ aspace_proxy_chain_filename }}"
        certificate_key_file: "{{ aspace_proxy_key_path }}/{{ aspace_proxy_key_filename }}"
        extra_parameters: |
          ProxyPass "/" "http://{{ aspace_proxy_production_backend_ip }}/"
          ProxyPassReverse "/" "http://{{ aspace_proxy_production_backend_ip }}/"

      - servername: "{{ aspace_proxy_test_hostname }}"
        certificate_file: "{{ aspace_proxy_cert_path }}/{{ aspace_proxy_cert_filename }}"
        certificate_chain_file: "{{ aspace_proxy_cert_path }}/{{ aspace_proxy_chain_filename }}"
        certificate_key_file: "{{ aspace_proxy_key_path }}/{{ aspace_proxy_key_filename }}"
        extra_parameters: |
          ProxyPass "/" "http://{{ aspace_proxy_test_backend_ip }}/"
          ProxyPassReverse "/" "http://{{ aspace_proxy_test_backend_ip }}/"
